name: star-q

volumes:
  postgres-data:

services:
  next-app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    depends_on:
      - migrate
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - ${CONTAINER_PORT:-3000}:3000
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    environment:
      PGPORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
  migrate:
    build:
      context: .
      dockerfile: migrate.Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./migrations:/app/migrations:ro
