name: annotation-tool

volumes:
  postgres-data:

services:
  next-app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: unless-stopped
    ports:
      - 3000:3000
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
